services:
  mongo:
    image: mongo:6
    container_name: docintel-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: docintel-backend
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/}
      - DOCINTEL_AI=${DOCINTEL_AI:-1}
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    command: uvicorn app.api.api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docintel-frontend
    depends_on:
      - backend
    environment:
      # The browser must call the host-exposed backend port
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"

volumes:
  mongo-data:
